#!/bin/bash

CMD=$1

if [[ -z "$CMD" ]]; then
  docker-compose build &&
  docker-compose up
  exit
fi

if [[ "$CMD" == "build" ]]; then
  docker-compose build
  exit
fi

if [[ "$CMD" == "test" ]]; then
  docker-compose run --rm search sh -c "npm install && npm test"
  exit
fi

docker-compose $@
